import { company } from "@/lib/company";
import { bgwDivision } from "@/lib/divisions";

/** Open Graph / Twitter / LinkedIn image specifications */
export const OG_IMAGE = {
  width: 1200,
  height: 630,
  aspectRatio: "1.91:1" as const,
  contentType: "image/png" as const,
  /** LinkedIn recommended minimum */
  linkedInMinWidth: 1200,
  linkedInMinHeight: 627,
} as const;

export const OG_IMAGE_PATHS = {
  /** Dynamic PNG generated by Next.js (primary) */
  default: "/opengraph-image",
  about: "/about/opengraph-image",
  services: "/services/opengraph-image",
  contact: "/contact/opengraph-image",
  /** Static SVG fallback in /public */
  staticDefault: "/og/ftbs-og-default.svg",
  staticAbout: "/og/ftbs-og-about.svg",
  staticServices: "/og/ftbs-og-services.svg",
  staticContact: "/og/ftbs-og-contact.svg",
} as const;

export type OgPageKey = "home" | "about" | "services" | "contact";

export type OgImageContent = {
  headline: string;
  subheadline: string;
  divisionLabel?: string;
  divisionTagline?: string;
  showBgw?: boolean;
};

export const OG_PAGE_CONTENT: Record<OgPageKey, OgImageContent> = {
  home: {
    headline: company.shortName,
    subheadline: company.tagline,
    divisionLabel: bgwDivision.shortName,
    divisionTagline: bgwDivision.tagline,
    showBgw: true,
  },
  about: {
    headline: "About FTBS",
    subheadline: "Finesse Technology Business Solutions",
    divisionLabel: bgwDivision.name,
    divisionTagline: "Infrastructure & community development",
    showBgw: true,
  },
  services: {
    headline: "Our Services",
    subheadline: "Construction project management & technology solutions",
    divisionLabel: bgwDivision.shortName,
    divisionTagline: "Roads · Buildings · Housing · Infrastructure",
    showBgw: true,
  },
  contact: {
    headline: "Contact FTBS",
    subheadline: "Partner on construction and infrastructure projects",
    divisionLabel: bgwDivision.shortName,
    divisionTagline: bgwDivision.tagline,
    showBgw: true,
  },
};

export function getOgImageAlt(content: OgImageContent): string {
  const bgw = content.showBgw
    ? ` — ${content.divisionLabel ?? bgwDivision.name}`
    : "";
  return `${content.headline}${bgw} | ${company.shortName}`;
}

/** Relative path to route-specific dynamic OG image */
export function getDynamicOgImagePath(pageKey: OgPageKey): string {
  const paths: Record<OgPageKey, string> = {
    home: OG_IMAGE_PATHS.default,
    about: OG_IMAGE_PATHS.about,
    services: OG_IMAGE_PATHS.services,
    contact: OG_IMAGE_PATHS.contact,
  };
  return paths[pageKey];
}

/** Relative path to route-specific dynamic Twitter image */
export function getDynamicTwitterImagePath(pageKey: OgPageKey): string {
  const paths: Record<OgPageKey, string> = {
    home: "/twitter-image",
    about: "/about/twitter-image",
    services: "/services/twitter-image",
    contact: "/contact/twitter-image",
  };
  return paths[pageKey];
}

export function getOgPageKeyFromPath(path: string): OgPageKey {
  if (path === "/about") return "about";
  if (path === "/services") return "services";
  if (path === "/contact") return "contact";
  return "home";
}